name: api
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  chopper: ^6.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  code_quality:
    path: ../code_quality
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  swagger_dart_code_generator: ^2.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
